<?php
session_start();
// Allow finance and studentservices roles
if (!isset($_SESSION['loggedin']) || !in_array($_SESSION['role'], ['finance', 'studentservices', 'admin'])) {
    header('Location: login.php');
    exit;
}
require_once 'includes/menu_helper.php';
require_once 'includes/db_config.php';
require_once 'includes/finance_sas_helper.php';

$conn = getDBConnection();
$fees_monitor = [];

// Get fees monitor schedule
if ($conn) {
    $tables_exist = $conn->query("SHOW TABLES LIKE 'student_schedules'")->num_rows > 0;
    
    if ($tables_exist) {
        $fees_monitor = getStudentSchedules('fees_monitor');
    }
    
    $conn->close();
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Fees Monitor - Finance/SAS</title>
  <link rel="stylesheet" href="../css/d_styles.css">
</head>
<body>
    <div class="dashboard-wrap container">
    <nav class="sidebar" aria-label="Main navigation">
      <div class="brand">
        <a href="<?php echo $_SESSION['role'] === 'finance' ? 'finance_dashboard.php' : 'student_service_dashboard.php'; ?>" style="display: flex; align-items: center; gap: 10px; text-decoration: none; color: inherit;">
          <img src="../images/pnmc.png" alt="logo"> 
          <strong>PNGMC</strong>
        </a>
      </div>
      <div class="menu">
        <?php if ($_SESSION['role'] === 'finance'): ?>
          <a class="menu-item" href="finance_dashboard.php">Dashboard</a>
          <div class="menu-section">Workflow</div>
          <a class="menu-item" href="proforma_invoices.php">Proforma Invoices</a>
          <a class="menu-item" href="student_schedules.php">Student Schedules</a>
          <a class="menu-item active" href="fees_monitor.php">Fees Monitor</a>
          <a class="menu-item" href="red_green_days.php">Red & Green Days</a>
          <a class="menu-item" href="finance_to_sas.php">Finance to SAS</a>
        <?php else: ?>
          <a class="menu-item" href="student_service_dashboard.php">Dashboard</a>
          <div class="menu-section">Workflow</div>
          <a class="menu-item" href="proforma_invoices.php">Proforma Invoices</a>
          <a class="menu-item" href="withdrawal_advice.php">Withdrawal Advice</a>
          <a class="menu-item" href="disciplinary_advice.php">Disciplinary Advice</a>
          <a class="menu-item" href="student_schedules.php">Student Schedules</a>
          <a class="menu-item active" href="fees_monitor.php">Fees Monitor</a>
        <?php endif; ?>
      </div>
    </nav>

    <div class="content">
      <header style="margin-bottom: 30px;">
        <h1>Fees Monitor Schedule</h1>
        <p class="small">
          <?php if ($_SESSION['role'] === 'studentservices' || $_SESSION['role'] === 'admin'): ?>
            Monitor fees for students currently attending programs/courses. Finance will be notified when schedule is generated.
          <?php else: ?>
            View Fees Monitor Schedule generated by Student Admin Service. This schedule is sent to Finance for review and MYOB synchronization.
          <?php endif; ?>
        </p>
      </header>

      <div class="main-card">
        <div style="margin-bottom: 20px;">
          <a href="student_schedules.php?type=fees_monitor" class="btn btn-primary" style="text-decoration: none; display: inline-block;">Generate/Update Fees Monitor Schedule</a>
        </div>

        <?php if (!empty($fees_monitor)): ?>
          <table style="width: 100%; border-collapse: collapse; margin-top: 20px;">
            <thead>
              <tr style="background: #1d4e89; color: white;">
                <th style="padding: 12px; text-align: left;">Student Number</th>
                <th style="padding: 12px; text-align: left;">Student Name</th>
                <th style="padding: 12px; text-align: left;">Program/Course Name</th>
                <th style="padding: 12px; text-align: left;">Start Date</th>
                <th style="padding: 12px; text-align: left;">Ending Date</th>
                <th style="padding: 12px; text-align: right;">Program/Course Fees</th>
                <th style="padding: 12px; text-align: right;">Total Payments</th>
                <th style="padding: 12px; text-align: right;">Outstanding</th>
                <th style="padding: 12px; text-align: left;">Remarks</th>
              </tr>
            </thead>
            <tbody>
              <?php foreach ($fees_monitor as $schedule): ?>
                <tr style="border-bottom: 1px solid #ddd;">
                  <td style="padding: 12px;"><?php echo htmlspecialchars($schedule['student_number']); ?></td>
                  <td style="padding: 12px;"><?php echo htmlspecialchars($schedule['student_name']); ?></td>
                  <td style="padding: 12px;"><?php echo htmlspecialchars($schedule['program_course_name']); ?></td>
                  <td style="padding: 12px;"><?php echo $schedule['program_course_start_date'] ? date('M d, Y', strtotime($schedule['program_course_start_date'])) : 'N/A'; ?></td>
                  <td style="padding: 12px;"><?php echo $schedule['program_course_ending_date'] ? date('M d, Y', strtotime($schedule['program_course_ending_date'])) : 'N/A'; ?></td>
                  <td style="padding: 12px; text-align: right;">PGK <?php echo number_format($schedule['program_course_tuition_fee'], 2); ?></td>
                  <td style="padding: 12px; text-align: right; color: #28a745;">PGK <?php echo number_format($schedule['amount_paid'], 2); ?></td>
                  <td style="padding: 12px; text-align: right; font-weight: bold; color: <?php echo $schedule['balance'] > 0 ? '#dc3545' : '#28a745'; ?>;">
                    PGK <?php echo number_format($schedule['balance'], 2); ?>
                  </td>
                  <td style="padding: 12px;"><?php echo htmlspecialchars($schedule['remarks'] ?? ''); ?></td>
                </tr>
              <?php endforeach; ?>
            </tbody>
          </table>
        <?php else: ?>
          <p style="color: #666; margin-top: 20px;">No fees monitor data found. <a href="student_schedules.php?type=fees_monitor">Generate Fees Monitor Schedule</a></p>
        <?php endif; ?>
      </div>
    </div>
  </div>
</body>
</html>

