<?php
session_start();
// Allow all roles
if (!isset($_SESSION['loggedin']) || !in_array($_SESSION['role'], ['admin', 'finance', 'studentservices', 'hod'])) {
    header('Location: login.php');
    exit;
}
require_once 'includes/menu_helper.php';
require_once 'includes/db_config.php';
require_once 'includes/finance_sas_helper.php';
require_once 'includes/workflow_helper.php';

$schedule_type = $_GET['type'] ?? 'currently_attending';
$conn = getDBConnection();
$schedules = [];
$students = [];

// Handle schedule generation
if ($_SERVER['REQUEST_METHOD'] === 'POST' && $conn) {
    $tables_exist = $conn->query("SHOW TABLES LIKE 'student_schedules'")->num_rows > 0;
    
    if ($tables_exist && isset($_POST['generate_schedule'])) {
        $type = $_POST['schedule_type'];
        
        // Get students based on type
        $sql = "SELECT s.*, e.enrollment_date, e.program_id, p.program_name, p.tuition_fee 
            FROM students s 
            LEFT JOIN enrollments e ON s.student_id = e.student_id 
            LEFT JOIN programs p ON e.program_id = p.program_id 
            WHERE s.status = 'active'";
        
        switch ($type) {
            case 'withdrawal':
                $sql .= " AND EXISTS (SELECT 1 FROM withdrawal_advice wa WHERE wa.student_id = s.student_id)";
                break;
            case 'disciplinary':
                $sql .= " AND EXISTS (SELECT 1 FROM disciplinary_advice da WHERE da.student_id = s.student_id)";
                break;
            case 'non_attending':
                $sql .= " AND NOT EXISTS (SELECT 1 FROM enrollments e2 WHERE e2.student_id = s.student_id AND e2.status = 'active')";
                break;
        }
        
        $result = $conn->query($sql);
        
        $generated = 0;
        while ($student = $result->fetch_assoc()) {
            // Get payment info
            $pi_result = $conn->query("SELECT 
                SUM(total_payments) as total_paid,
                balance,
                pi_number,
                revised_pi_number
            FROM proforma_invoices 
            WHERE student_id = {$student['student_id']} 
            ORDER BY pi_id DESC LIMIT 1");
            $pi_data = $pi_result->fetch_assoc();
            
            $data = [
                'student_number' => $student['student_number'],
                'student_name' => $student['first_name'] . ' ' . $student['last_name'],
                'student_address' => $student['address'] ?? '',
                'sponsor_name' => null, // Would need sponsor table
                'sponsor_type' => null,
                'program_course_name' => $student['program_name'] ?? 'N/A',
                'program_course_start_date' => $student['enrollment_date'] ?? null,
                'program_course_ending_date' => null, // Would calculate from program duration
                'program_course_tuition_fee' => floatval($student['tuition_fee'] ?? 0),
                'amount_paid' => floatval($pi_data['total_paid'] ?? 0),
                'balance' => floatval($pi_data['balance'] ?? 0),
                'dates_fees_paid' => null, // Would need to aggregate from payments
                'proforma_invoice_number' => $pi_data['pi_number'] ?? null,
                'revised_pi_number' => $pi_data['revised_pi_number'] ?? null,
                'remarks' => ''
            ];
            
            // Add type-specific data
            if ($type === 'disciplinary') {
                $da_result = $conn->query("SELECT * FROM disciplinary_advice WHERE student_id = {$student['student_id']} ORDER BY disciplinary_id DESC LIMIT 1");
                if ($da_result && $da_result->num_rows > 0) {
                    $da = $da_result->fetch_assoc();
                    $data['disciplinary_reason'] = $da['reason'];
                    $data['disciplinary_action'] = $da['action_taken'];
                    $data['fee_amendment'] = $da['fee_amendment'];
                    $data['amendment_type'] = $da['amendment_type'];
                }
            } elseif ($type === 'withdrawal') {
                $wa_result = $conn->query("SELECT * FROM withdrawal_advice WHERE student_id = {$student['student_id']} ORDER BY withdrawal_id DESC LIMIT 1");
                if ($wa_result && $wa_result->num_rows > 0) {
                    $wa = $wa_result->fetch_assoc();
                    $data['withdrawal_reason'] = $wa['reason'];
                    $data['withdrawal_action'] = $wa['action_taken'];
                    $data['fee_amendment'] = $wa['fee_amendment'];
                    $data['amendment_type'] = $wa['amendment_type'];
                }
            }
            
            if (createStudentSchedule($type, $student['student_id'], $data)) {
                $generated++;
            }
        }
        
        // If generated by Student Admin Service, notify Finance
        if ($generated > 0 && ($_SESSION['role'] === 'studentservices' || $_SESSION['role'] === 'admin')) {
            $schedule_type_names = [
                'currently_attending' => 'Students Currently Attending Schedule',
                'withdrawal' => 'Withdrawal Students Schedule',
                'disciplinary' => 'Disciplinary Students Schedule',
                'non_attending' => 'Non Attending Students Schedule',
                'fees_monitor' => 'Fees Monitor Schedule',
                'red_green_days' => 'Red & Green Days Schedule'
            ];
            
            $schedule_name = $schedule_type_names[$type] ?? ucfirst(str_replace('_', ' ', $type)) . ' Schedule';
            
            $notification_title = "📊 " . $schedule_name . " from Student Admin Service";
            $notification_message = "A new " . $schedule_name . " has been generated:\n\nSchedule Type: " . $schedule_name . "\nStudents Processed: {$generated}\n\nPlease review the schedule for financial updates and MYOB synchronization.";
            
            createWorkflowNotification(
                0, // Not application-related
                'studentservices',
                'finance',
                $notification_title,
                $notification_message,
                'information',
                'student_schedules.php?type=' . $type,
                $_SESSION['user_id']
            );
        }
        
        $message = "Schedule generated successfully! $generated students processed." . 
            ($generated > 0 && ($_SESSION['role'] === 'studentservices' || $_SESSION['role'] === 'admin') ? "<br><br>✅ Finance has been notified." : "");
        $message_type = "success";
    }
}

// Get schedules
if ($conn) {
    $tables_exist = $conn->query("SHOW TABLES LIKE 'student_schedules'")->num_rows > 0;
    
    if ($tables_exist) {
        $schedules = getStudentSchedules($schedule_type);
    }
    
    // Get students for generation
    $result = $conn->query("SELECT s.*, p.program_name FROM students s 
        LEFT JOIN enrollments e ON s.student_id = e.student_id 
        LEFT JOIN programs p ON e.program_id = p.program_id 
        WHERE s.status = 'active' 
        ORDER BY s.first_name, s.last_name");
    if ($result) {
        $students = $result->fetch_all(MYSQLI_ASSOC);
    }
    
    $conn->close();
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Student Schedules - Finance/SAS</title>
  <link rel="stylesheet" href="../css/d_styles.css">
  <link rel="stylesheet" href="../css/responsive.css">
  <style>
    .schedule-tabs {
      display: flex;
      gap: 10px;
      margin-bottom: 20px;
      flex-wrap: wrap;
    }
    .schedule-tab {
      padding: 10px 20px;
      background: #f8f9fa;
      border: 2px solid #ddd;
      border-radius: 5px;
      cursor: pointer;
      font-weight: 600;
      transition: all 0.2s;
    }
    .schedule-tab:hover {
      background: #e9ecef;
    }
    .schedule-tab.active {
      background: #1d4e89;
      color: white;
      border-color: #1d4e89;
    }
  </style>
</head>
<body>
    <div class="dashboard-wrap container">
    <nav class="sidebar" aria-label="Main navigation">
      <div class="brand">
        <a href="<?php echo $_SESSION['role'] === 'finance' ? 'finance_dashboard.php' : 'student_service_dashboard.php'; ?>" style="display: flex; align-items: center; gap: 10px; text-decoration: none; color: inherit;">
          <img src="../images/pnmc.png" alt="logo"> 
          <strong>PNGMC</strong>
        </a>
      </div>
      <div class="menu">
        <?php if ($_SESSION['role'] === 'finance'): ?>
          <a class="menu-item" href="finance_dashboard.php">Dashboard</a>
          <div class="menu-section">Workflow</div>
          <a class="menu-item" href="proforma_invoices.php">Proforma Invoices</a>
          <a class="menu-item active" href="student_schedules.php">Student Schedules</a>
          <a class="menu-item" href="fees_monitor.php">Fees Monitor</a>
          <a class="menu-item" href="red_green_days.php">Red & Green Days</a>
          <a class="menu-item" href="finance_to_sas.php">Finance to SAS</a>
        <?php else: ?>
          <a class="menu-item" href="student_service_dashboard.php">Dashboard</a>
          <div class="menu-section">Workflow</div>
          <a class="menu-item" href="proforma_invoices.php">Proforma Invoices</a>
          <a class="menu-item" href="withdrawal_advice.php">Withdrawal Advice</a>
          <a class="menu-item" href="disciplinary_advice.php">Disciplinary Advice</a>
          <a class="menu-item active" href="student_schedules.php">Student Schedules</a>
        <?php endif; ?>
      </div>
    </nav>

    <div class="content">
      <header style="margin-bottom: 30px;">
        <h1>Student Schedules</h1>
        <p class="small">
          <?php if ($_SESSION['role'] === 'studentservices' || $_SESSION['role'] === 'admin'): ?>
            Generate and view student schedules: Currently Attending, Withdrawal, Disciplinary, Non Attending, Fees Monitor, Red & Green Days. Finance will be notified when schedules are generated.
          <?php else: ?>
            View student schedules generated by Student Admin Service. These schedules are sent to Finance for review and MYOB synchronization.
          <?php endif; ?>
        </p>
      </header>

      <?php if (isset($message)): ?>
        <div class="message <?php echo $message_type; ?>" style="padding: 15px; margin-bottom: 20px; border-radius: 5px; background: <?php echo $message_type === 'success' ? '#d4edda' : '#f8d7da'; ?>; color: <?php echo $message_type === 'success' ? '#155724' : '#721c24'; ?>;">
          <?php echo htmlspecialchars($message); ?>
        </div>
      <?php endif; ?>

      <div class="schedule-tabs">
        <a href="student_schedules.php?type=currently_attending" class="schedule-tab <?php echo $schedule_type === 'currently_attending' ? 'active' : ''; ?>">Currently Attending</a>
        <a href="student_schedules.php?type=withdrawal" class="schedule-tab <?php echo $schedule_type === 'withdrawal' ? 'active' : ''; ?>">Withdrawal</a>
        <a href="student_schedules.php?type=disciplinary" class="schedule-tab <?php echo $schedule_type === 'disciplinary' ? 'active' : ''; ?>">Disciplinary</a>
        <a href="student_schedules.php?type=non_attending" class="schedule-tab <?php echo $schedule_type === 'non_attending' ? 'active' : ''; ?>">Non Attending</a>
        <a href="student_schedules.php?type=fees_monitor" class="schedule-tab <?php echo $schedule_type === 'fees_monitor' ? 'active' : ''; ?>">Fees Monitor</a>
        <a href="student_schedules.php?type=red_green_days" class="schedule-tab <?php echo $schedule_type === 'red_green_days' ? 'active' : ''; ?>">Red & Green Days</a>
      </div>

      <div class="main-card" style="margin-bottom: 20px;">
        <h2>Generate Schedule</h2>
        <form method="POST">
          <input type="hidden" name="schedule_type" value="<?php echo htmlspecialchars($schedule_type); ?>">
          <p>Generate <?php echo ucfirst(str_replace('_', ' ', $schedule_type)); ?> schedule for all eligible students.</p>
          <button type="submit" name="generate_schedule" class="btn btn-primary">Generate Schedule</button>
        </form>
      </div>

      <div class="main-card">
        <h2><?php echo ucfirst(str_replace('_', ' ', $schedule_type)); ?> Schedule</h2>
        <?php if (!empty($schedules)): ?>
          <table style="width: 100%; border-collapse: collapse; margin-top: 20px; font-size: 0.9rem;">
            <thead>
              <tr style="background: #1d4e89; color: white;">
                <th style="padding: 12px; text-align: left;">Student Number</th>
                <th style="padding: 12px; text-align: left;">Student Name</th>
                <?php if ($schedule_type === 'currently_attending'): ?>
                  <th style="padding: 12px; text-align: left;">Sponsor</th>
                <?php endif; ?>
                <th style="padding: 12px; text-align: left;">Program/Course</th>
                <th style="padding: 12px; text-align: left;">Start Date</th>
                <th style="padding: 12px; text-align: left;">Ending Date</th>
                <th style="padding: 12px; text-align: right;">Tuition Fee</th>
                <th style="padding: 12px; text-align: right;">Amount Paid</th>
                <th style="padding: 12px; text-align: right;">Balance</th>
                <?php if ($schedule_type === 'disciplinary'): ?>
                  <th style="padding: 12px; text-align: left;">Reason</th>
                  <th style="padding: 12px; text-align: left;">Action</th>
                <?php endif; ?>
                <?php if ($schedule_type === 'withdrawal'): ?>
                  <th style="padding: 12px; text-align: left;">Reason</th>
                  <th style="padding: 12px; text-align: left;">Action</th>
                <?php endif; ?>
                <?php if ($schedule_type === 'red_green_days'): ?>
                  <th style="padding: 12px; text-align: center;">Days Paid</th>
                  <th style="padding: 12px; text-align: center;">Days Non Paid</th>
                  <th style="padding: 12px; text-align: center;">Alert</th>
                <?php endif; ?>
                <th style="padding: 12px; text-align: left;">PI Number</th>
              </tr>
            </thead>
            <tbody>
              <?php foreach ($schedules as $schedule): ?>
                <tr style="border-bottom: 1px solid #ddd;">
                  <td style="padding: 12px;"><?php echo htmlspecialchars($schedule['student_number']); ?></td>
                  <td style="padding: 12px;"><?php echo htmlspecialchars($schedule['student_name']); ?></td>
                  <?php if ($schedule_type === 'currently_attending'): ?>
                    <td style="padding: 12px;">
                      <?php echo htmlspecialchars($schedule['sponsor_name'] ?? 'N/A'); ?><br>
                      <small style="color: #666;"><?php echo $schedule['sponsor_type'] ? ucfirst(str_replace('_', ' ', $schedule['sponsor_type'])) : ''; ?></small>
                    </td>
                  <?php endif; ?>
                  <td style="padding: 12px;"><?php echo htmlspecialchars($schedule['program_course_name']); ?></td>
                  <td style="padding: 12px;"><?php echo $schedule['program_course_start_date'] ? date('M d, Y', strtotime($schedule['program_course_start_date'])) : 'N/A'; ?></td>
                  <td style="padding: 12px;"><?php echo $schedule['program_course_ending_date'] ? date('M d, Y', strtotime($schedule['program_course_ending_date'])) : 'N/A'; ?></td>
                  <td style="padding: 12px; text-align: right;">PGK <?php echo number_format($schedule['program_course_tuition_fee'], 2); ?></td>
                  <td style="padding: 12px; text-align: right; color: #28a745;">PGK <?php echo number_format($schedule['amount_paid'], 2); ?></td>
                  <td style="padding: 12px; text-align: right; font-weight: bold; color: #dc3545;">PGK <?php echo number_format($schedule['balance'], 2); ?></td>
                  <?php if ($schedule_type === 'disciplinary'): ?>
                    <td style="padding: 12px;"><?php echo $schedule['disciplinary_reason'] ? ucfirst(str_replace('_', ' ', $schedule['disciplinary_reason'])) : 'N/A'; ?></td>
                    <td style="padding: 12px;"><?php echo $schedule['disciplinary_action'] ? ucfirst(str_replace('_', ' ', $schedule['disciplinary_action'])) : 'N/A'; ?></td>
                  <?php endif; ?>
                  <?php if ($schedule_type === 'withdrawal'): ?>
                    <td style="padding: 12px;"><?php echo $schedule['withdrawal_reason'] ? ucfirst(str_replace('_', ' ', $schedule['withdrawal_reason'])) : 'N/A'; ?></td>
                    <td style="padding: 12px;"><?php echo $schedule['withdrawal_action'] ? ucfirst(str_replace('_', ' ', $schedule['withdrawal_action'])) : 'N/A'; ?></td>
                  <?php endif; ?>
                  <?php if ($schedule_type === 'red_green_days'): ?>
                    <td style="padding: 12px; text-align: center;"><?php echo $schedule['days_paid'] ?? 0; ?></td>
                    <td style="padding: 12px; text-align: center;"><?php echo $schedule['days_non_paid'] ?? 0; ?></td>
                    <td style="padding: 12px; text-align: center;">
                      <?php if ($schedule['alert_flag']): ?>
                        <span style="padding: 4px 8px; border-radius: 3px; background: <?php 
                          echo $schedule['alert_flag'] === 'red' ? '#dc3545' : ($schedule['alert_flag'] === 'yellow' ? '#ffc107' : '#28a745');
                        ?>; color: white; font-size: 0.85rem;">
                          <?php echo strtoupper($schedule['alert_flag']); ?>
                        </span>
                      <?php endif; ?>
                    </td>
                  <?php endif; ?>
                  <td style="padding: 12px;">
                    <?php echo htmlspecialchars($schedule['proforma_invoice_number'] ?? 'N/A'); ?>
                    <?php if ($schedule['revised_pi_number']): ?>
                      <br><small style="color: #666;">Revised: <?php echo htmlspecialchars($schedule['revised_pi_number']); ?></small>
                    <?php endif; ?>
                  </td>
                </tr>
              <?php endforeach; ?>
            </tbody>
          </table>
        <?php else: ?>
          <p style="color: #666; margin-top: 20px;">No schedules found for this type. Click "Generate Schedule" to create one.</p>
        <?php endif; ?>
      </div>
    </div>
  </div>
</body>
</html>

